### ISSUE TITLE
Pet-Cuddle-O-Tron | CORS issue between S3 and API gateway

### ISSUE THREAD

**Issue by raunak111** [acantril/learn-cantrill-io-labs#72]
CORS is enabled on the API created. Verified using the curl command below:

![image](https://user-images.githubusercontent.com/37953138/193156134-00aab810-530e-44a0-9f65-cd6eb307fb92.png)

After submitting values from the S3 static website, I get this error:

`
Access to fetch at 'https://hfg9swflk0.execute-api.us-east-1.amazonaws.com/prod/petcuddleotron' from origin 'http://petcuddleotron9007.s3-website-us-east-1.amazonaws.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
`

![image](https://user-images.githubusercontent.com/37953138/193156376-e7d9d3f7-9abd-43b6-85da-86ae7261fbbf.png)

**Comment by acantril** [comment]
What do your lambda logs show ?
For the api_handler function.

**Comment by acantril** [comment]
The error is typeerror, which is not a CORS error.
I suspect you have misclicked one of the boxes while setting up API Gateway or not edited the api_handler function correctly.
If you paste the logs for this lambda function we can diagnose.

**Comment by acantril** [comment]
Ok so it looks like you have deleted it ... I'm going to go ahead and close this issue. 
No diagnosis can be done without the infrastructure in place.

**Comment by raunak111** [comment]
I checked the logs of the lambda function, and it was blank. 
The first step of sending the data from our website to the api is not happening. 
So the api never called the lambda function in the proceeding step

**Comment by raunak111** [comment]
I'm sorry adrian, didn't realize you were debugging it from your end. 
I proceeded in the course and followed stage6 which was cleanup

**Comment by raunak111** [comment]
> Ok so it looks like you have deleted it ... I'm going to go ahead and close this issue. No diagnosis can be done without the infrastructure in place.
I'm sorry adrian, didn't realize you were debugging it from your end.
I proceeded in the course and followed stage6 which was cleanup

**Comment by raunak111** [comment]
> Ok so it looks like you have deleted it ... I'm going to go ahead and close this issue. No diagnosis can be done without the infrastructure in place.

I'm sorry adrian, didn't realize you were debugging it from your end.
I proceeded in the course and followed stage6 which was cleanup

**Comment by acantril** [comment]
Yeah this is not how you should be working through a course
If you hit an issue, you should be looking to diagnose why... that's the
best way to learn
What you have done here is report an issue, and then delete the
infrastructure
This doesn't help you learn, and regardless of if this is a mistake you
did, or a bug with the demo ... I have no way of understanding the
information at your side.

It's pointless having the issue open, as there's no way to make progress on
it.

**Comment by raunak111** [comment]
I recreated my issue, and created admin credentials for you and sent it on adrian@cantrill.io

S3 website: http://petcuddleotron9007.s3-website-us-east-1.amazonaws.com/
API URL: https://x225ufa561.execute-api.us-east-1.amazonaws.com/prod
Lambda code: 
![image](https://user-images.githubusercontent.com/37953138/193166152-82e34faf-2761-4c1b-8e88-b5e45c9b9751.png)

Debugging just the beginning of website+api+lambda would be sufficient for me, so didn't create the whole infrastructure

**Comment by acantril** [comment]
You told me before that your lambda logs were empty ?
I've just looked and they are anything but empty

The log is full of permissions errors

2022-09-30T09:09:52.323+10:00
[ERROR] ClientError: An error occurred (AccessDeniedException) when calling
the StartExecution operation: User:
arn:aws:sts::753173683840:assumed-role/api_lambda-role-v7qgm771/api_lambda
is not authorized to perform: states:StartExecution on resource:
arn:aws:states:us-east-1:753173683840:stateMachine:PetCuddleOTron because
no identity-based policy allows the states:StartExecution action
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 41, in lambda_handler
    sm.start_execution( stateMachineArn=SM_ARN, input=json.dumps(data,
cls=DecimalEncoder) )
  File "/var/runtime/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)

This means that your previous lambda didn't have permissions to execute the
state machine, and thus was failing, which would have been why the
APIGateway integration would have failed.
Did you actually give lambda the execution role that was created via the
cloud formation stack you applied ? This suggests you didn't.
