### ISSUE TITLE
Hybridlab error

### ISSUE THREAD

**Issue by vuhondat** [acantril/learn-cantrill-io-labs#8]
Hi Adrian,

I'm in the session Hybrid demo:

[DEMO] Implementing a hybrid directory solution in AWS - PART1
I'd tried to provision by use your link:

https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/quickcreate?templateURL=https://learn-cantrill-labs.s3.amazonaws.com/aws-hybrid-activedirectory/01_HYBRIDDIR.yaml&stackName=HYBRIDDIR 
 
And the error appear:

Embedded stack arn:aws:cloudformation:us-east-1:792286733653:stack/HYBRIDDIR-ONPREMAD-14D1JLDNZTKHI/e8098230-370a-11eb-918b-0ed5acf75591 was not successfully created: The following resource(s) failed to create: [DomainController2]. 

Kindly check and advice.

Thanks so much.

Vuhondat

**Comment by cosminilie** [comment]
Had the same issue today. Seems the problem happens at "dcsInstallDscModules" when it installs the install-ad-modules.ps1.

The command output is:

```
Installing NuGet Package Provider

Name Version Source Summary

---- ------- ------ -------

nuget 2.8.5.208 https://onege... NuGet provider for the OneGet meta-package manager

Setting PSGallery Respository to trusted

Installing the needed Powershell DSC modules for this Quick Start

Temporarily disabling Windows Firewall

Creating Directory for DSC Public Cert

Failed to create publickeys directory An item with the specified name C:\AWSQuickstart\publickeys already exists.

----------ERROR-------

failed to run commands: exit status 255
```

Seems the script tries to create the folder and fails if it can't
https://aws-quickstart-us-east-1.s3.us-east-1.amazonaws.com/quickstart-fsx-windows-file-server/submodules/quickstart-microsoft-activedirectory/scripts/install-ad-modules.ps1

```
#line 67-73
Write-Output 'Creating Directory for DSC Public Cert'
Try {
    New-Item -Path 'C:\AWSQuickstart\publickeys' -ItemType 'Directory' -ErrorAction Stop
} Catch [System.Exception] {
    Write-Output "Failed to create publickeys directory $_"
    Exit 1
}
```

**Comment by gfandino** [comment]
Hi Adrian,

I was trying to do the LAB for [DEMO] Implementing a hybrid directory solution in AWS - PART1

As mention before, I'd tried to provision thru your link

https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/quickcreate?templateURL=https://learn-cantrill-labs.s3.amazonaws.com/aws-hybrid-activedirectory/01_HYBRIDDIR.yaml&stackName=HYBRIDDIR

But CF Template HYBRIDDIR-ONPREMAD-I6JXLFJ1P5DA, it got stuck on the creation of the DomainController2, it seems to be that signal in CF template have something wrong, because the EC2 Instance for Domain Controller 2, is created sucessfully but, the CF did not move forward.

After one hour, it gave me the same error as Vuhondat.

I would appreciated your check and solving the issue.

Thank you in advance.

Gustavo.

**Comment by acantril** [comment]
Hi, generally this is due to the AD domain admin password you have picked.
You are posting this on an existing issue thread, is this the same issue?

**Comment by gfandino** [comment]
> Hi, generally this is due to the AD domain admin password you have picked.
> You are posting this on an existing issue thread, is this the same issue?

Hi Adrian.

Thank you so much for the quick response!. 

Is the same issue, I did try to pick another password and it worked.

Thank you so much.

Regards.
